./prod2pic.sh 'New Balance ML574LUE'
./prod2pic.sh 'Umbro Boty Runner Royal/Sil'
./prod2pic.sh 'Columbia Peakfreak Venture'
./prod2pic.sh 'KEEN Basin Wp Jr'
./prod2pic.sh 'Vans Atwood Low (Canvas) Black/Black'
./prod2pic.sh 'Umbro Boty Runner 2 White'
./prod2pic.sh 'Puma ST Trainer Evo Demi v2 Corduroy'
./prod2pic.sh 'Mammut Pordoi Mid Women'
./prod2pic.sh 'Salomon Rx Break Lime Punch/Cloisonné'
./prod2pic.sh 'Nike MD Runner 2 (PS) Pre-School Shoe'
./prod2pic.sh 'Nike Women\S Benassi "Just Do It" Sandal'
./prod2pic.sh 'Crocs Crocband'
./prod2pic.sh '"Nike WomenS Kawa Shower Sandal"'
./prod2pic.sh 'KEEN Galleo Mid Wp M'
./prod2pic.sh 'Crocs Yukon Mesa Clog M'
./prod2pic.sh 'Converse Chuck Taylor All Star Dainty'
./prod2pic.sh 'KEEN Newport H2 K Racer Gray'
./prod2pic.sh 'KEEN Revel III M'
./prod2pic.sh 'KEEN Wanderer Mid Wp M'
